version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 14
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
      - tfenv  remote-list
      
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
    - appspec.yml
